name: Generate Snake

# Controls when the action will run. This action runs every 6 hours.

on:
  push:

# This command allows us to run the Action automatically from the Actions tab.
  workflow_dispatch:

# The sequence of runs in this workflow:
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    
    # Checks repo under $GITHUB_WORKSHOP, so your job can access it
      - uses: actions/checkout@v2
      
    # Generates the snake  

      - name: Docker Metadata action
        uses: docker/metadata-action@v3.6.2
        with:
          images: name/gannaramu
          tags: |
              type=semver,pattern={{version}}
              type=semver,pattern={{major}}.{{minor}}
